# factory.py - Universal AI Agent Factory
import httpx
import asyncio
import os
import json
import re
import importlib.util
from typing import Dict, Any, List
from datetime import datetime

class ResearchFactory:
    def __init__(self):
        self.neurons_dir = "neurons"
        os.makedirs(self.neurons_dir, exist_ok=True)
        self.agents_dir = "agents"
        os.makedirs(self.agents_dir, exist_ok=True)
        self.client = httpx.AsyncClient(timeout=30.0)
        
    async def research_failure(self, error: str, task: str) -> Dict[str, Any]:
        """Research any failure online"""
        try:
            searches = [
                f"{task} how to implement",
                f"{error} solution fix",
                f"{task} tutorial example"
            ]
            
            all_text = []
            sources = []
            
            for query in searches:
                try:
                    response = await self.client.get(
                        "https://api.duckduckgo.com/",
                        params={"q": query, "format": "json", "no_html": 1}
                    )
                    data = response.json()
                    if data.get("AbstractText"):
                        all_text.append(data["AbstractText"])
                        if data.get("AbstractURL"):
                            sources.append(data["AbstractURL"])
                except:
                    pass
            
            summary = " | ".join(all_text) if all_text else f"Researching: {task}"
            
            return {
                "summary": summary[:500],
                "sources": sources,
                "suggested_fix": "build_agent",
                "task_category": "general"
            }
        except Exception as e:
            return {
                "summary": f"Research error: {str(e)}",
                "sources": [],
                "suggested_fix": "build_agent"
            }
    
    async def build_fix(self, error: str, research: Dict, task: str) -> Dict[str, Any]:
        """Build the right agent for the task"""
        task_lower = task.lower()
        
        if any(w in task_lower for w in ["website", "webpage", "html", "site"]):
            return await self._build_website_agent(task, research)
        elif any(w in task_lower for w in ["code", "program", "function", "script"]):
            return await self._build_code_agent(task, research)
        elif any(w in task_lower for w in ["hello", "hi", "hey", "greet", "wetin", "how far"]):
            return await self._build_greeting_agent(task, research)
        elif any(w in task_lower for w in ["search", "find", "lookup", "what is", "who is"]):
            return await self._build_search_agent(task, research)
        elif any(w in task_lower for w in ["calculate", "math", "solve", "equation"]):
            return await self._build_math_agent(task, research)
        elif any(w in task_lower for w in ["write", "essay", "story", "poem", "content"]):
            return await self._build_writer_agent(task, research)
        elif any(w in task_lower for w in ["translate", "language", "meaning"]):
            return await self._build_translator_agent(task, research)
        else:
            return await self._build_universal_agent(task, research)
    
    async def _build_website_agent(self, task, research):
        name = f"web_agent_{int(datetime.now().timestamp())}"
        code = """
import json

async def fire(task: dict) -> dict:
    text = task.get("text", "").lower()
    help_info = task.get("help_info", "")
    
    use_tailwind = "tailwind" in help_info.lower() if help_info else False
    dark = "dark" in text or ("dark" in help_info.lower() if help_info else False)
    
    if use_tailwind:
        bg = "bg-gray-900" if dark else "bg-white"
        tc = "text-white" if dark else "text-gray-900"
        html = '<!DOCTYPE html>\\n<html lang=\"en\">\\n<head>\\n<meta charset=\"UTF-8\">\\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\\n<title>My Website</title>\\n<script src=\"https://cdn.tailwindcss.com\"></script>\\n</head>\\n<body class=\"' + bg + ' ' + tc + ' min-h-screen\">\\n<nav class=\"border-b p-4\"><div class=\"container mx-auto flex justify-between\"><h1 class=\"text-2xl font-bold\">MySite</h1><div class=\"space-x-4\"><a href=\"#\">Home</a><a href=\"#\">About</a><a href=\"#\">Contact</a></div></div></nav>\\n<main class=\"container mx-auto text-center py-20\"><h2 class=\"text-5xl font-bold mb-4\">Welcome</h2><p class=\"text-xl mb-8\">Generated by UAI Brain</p><button class=\"bg-blue-500 hover:bg-blue-600 px-8 py-3 rounded-lg font-semibold\">Get Started</button></main>\\n<section class=\"container mx-auto grid grid-cols-3 gap-8 py-16 px-4\"><div class=\"p-8 border rounded-xl text-center\"><div class=\"text-4xl mb-4\">🚀</div><h3 class=\"text-xl font-bold\">Fast</h3><p>Lightning performance</p></div><div class=\"p-8 border rounded-xl text-center\"><div class=\"text-4xl mb-4\">🎨</div><h3 class=\"text-xl font-bold\">Beautiful</h3><p>Modern design</p></div><div class=\"p-8 border rounded-xl text-center\"><div class=\"text-4xl mb-4\">🤖</div><h3 class=\"text-xl font-bold\">AI-Powered</h3><p>Built by UAI</p></div></section>\\n</body>\\n</html>'
    else:
        bg = "#1a1a2e" if dark else "#f0f0f0"
        tc = "#fff" if dark else "#333"
        html = '<!DOCTYPE html>\\n<html lang=\"en\">\\n<head>\\n<meta charset=\"UTF-8\">\\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\\n<title>My Website</title>\\n<style>\\n*{margin:0;padding:0;box-sizing:border-box}\\nbody{font-family:Arial,sans-serif;background:' + bg + ';color:' + tc + ';min-height:100vh}\\nnav{display:flex;justify-content:space-between;padding:1rem 2rem;background:rgba(0,0,0,0.1)}\\nnav h1{font-size:1.5rem}\\nnav ul{display:flex;list-style:none;gap:2rem}\\nnav a{color:' + tc + ';text-decoration:none}\\n.hero{text-align:center;padding:6rem 2rem}\\n.hero h2{font-size:3rem;margin-bottom:1rem}\\n.hero p{font-size:1.2rem;opacity:0.8}\\n.btn{display:inline-block;margin-top:2rem;padding:1rem 2rem;background:#4a90d9;color:#fff;text-decoration:none;border-radius:50px}\\n.features{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:2rem;padding:4rem 2rem;max-width:1200px;margin:0 auto}\\n.feature-card{background:rgba(255,255,255,0.1);padding:2rem;border-radius:1rem;text-align:center}\\n</style>\\n</head>\\n<body>\\n<nav><h1>MySite</h1><ul><li><a href=\"#\">Home</a></li><li><a href=\"#\">About</a></li><li><a href=\"#\">Contact</a></li></ul></nav>\\n<section class=\"hero\"><h2>Welcome</h2><p>Generated by UAI Brain - Self-Evolving AI</p><a href=\"#\" class=\"btn\">Get Started</a></section>\\n<section class=\"features\"><div class=\"feature-card\"><h3>🚀</h3><h4>Fast</h4><p>Lightning performance</p></div><div class=\"feature-card\"><h3>🎨</h3><h4>Beautiful</h4><p>Modern design</p></div><div class=\"feature-card\"><h3>🤖</h3><h4>AI-Powered</h4><p>Built by UAI</p></div></section>\\n</body>\\n</html>'
    
    return {"success": True, "answer": html, "format": "html", "message": "Website generated! Save as .html file to view."}
"""
        return await self._save_agent(name, code)
    
    async def _build_code_agent(self, task, research):
        name = f"code_agent_{int(datetime.now().timestamp())}"
        code = """
async def fire(task: dict) -> dict:
    text = task.get("text", "").lower()
    
    if "python" in text:
        lang = "python"
        result = '''def main():
    print("Hello from UAI Brain!")
    print("This Python code was auto-generated.")
    
    data = [1, 2, 3, 4, 5]
    total = sum(data)
    print(f"Sum: {total}")
    return total

if __name__ == "__main__":
    main()'''
    elif "javascript" in text or "js" in text:
        lang = "javascript"
        result = '''function main() {
    console.log("Hello from UAI Brain!");
    console.log("This JavaScript code was auto-generated.");
    
    const data = [1, 2, 3, 4, 5];
    const total = data.reduce((a, b) => a + b, 0);
    console.log("Sum: " + total);
    return total;
}

main();'''
    else:
        lang = "python"
        result = '''# Auto-generated by UAI Brain
def main():
    print("Hello from UAI Brain!")
    print("Specify a language like 'write python code' or 'write javascript code'")

if __name__ == "__main__":
    main()'''
    
    return {"success": True, "answer": "```" + lang + "\\n" + result + "\\n```", "language": lang, "code": result}
"""
        return await self._save_agent(name, code)
    
    async def _build_greeting_agent(self, task, research):
        name = f"greet_agent_{int(datetime.now().timestamp())}"
        code = """
import random

async def fire(task: dict) -> dict:
    text = task.get("text", "").lower()
    
    if any(w in text for w in ["wetin", "how far", "how you dey"]):
        return {"success": True, "answer": "I dey o! How you dey? 🇳🇬\\n\\nThat\\'s Nigerian Pidgin for \\'I\\'m fine, how are you?\\'\\n\\nWhat can I help you with today?"}
    
    greetings = [
        "Hello! I\\'m UAI Brain, your self-evolving AI. I can build websites, write code, search the web, solve math, and more! What would you like?",
        "Hi there! I\\'m UAI - I learn and build new AI agents in real-time. Need help? Just ask!",
        "Hey! Ready to help with anything - websites, code, research, calculations, writing. What do you need?",
        "Greetings! I\\'m an AI that evolves by building new agents for each task. Try asking me to make a website or solve a problem!"
    ]
    
    return {"success": True, "answer": random.choice(greetings), "type": "greeting"}
"""
        return await self._save_agent(name, code)
    
    async def _build_search_agent(self, task, research):
        name = f"search_agent_{int(datetime.now().timestamp())}"
        code = """
import httpx

async def fire(task: dict) -> dict:
    text = task.get("text", "")
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        try:
            response = await client.get("https://api.duckduckgo.com/", params={"q": text, "format": "json"})
            data = response.json()
            answer = data.get("AbstractText", "")
            
            if answer:
                source = data.get("AbstractURL", "")
                return {"success": True, "answer": answer + "\\n\\nSource: " + source if source else answer}
            
            related = data.get("RelatedTopics", [])
            if related:
                topics = []
                for t in related[:5]:
                    if isinstance(t, dict) and "Text" in t:
                        topics.append("• " + t["Text"])
                return {"success": True, "answer": "Found:\\n\\n" + "\\n".join(topics)}
            
            return {"success": True, "answer": "I searched for '" + text + "' but found no specific results. Try rephrasing!"}
        except Exception as e:
            return {"success": True, "answer": "Search error: " + str(e)}
"""
        return await self._save_agent(name, code)
    
    async def _build_math_agent(self, task, research):
        name = f"math_agent_{int(datetime.now().timestamp())}"
        code = """
import math
import re

async def fire(task: dict) -> dict:
    text = task.get("text", "")
    
    # Try to find arithmetic expression
    pattern = r'(-?\\d+\\.?\\d*)\\s*([+\\-*/^])\\s*(-?\\d+\\.?\\d*)'
    match = re.search(pattern, text)
    
    if match:
        n1 = float(match.group(1))
        op = match.group(2)
        n2 = float(match.group(3))
        
        if op == '+': result = n1 + n2
        elif op == '-': result = n1 - n2
        elif op == '*': result = n1 * n2
        elif op == '/': result = n1 / n2 if n2 != 0 else "undefined"
        elif op == '^': result = n1 ** n2
        
        return {"success": True, "answer": f"{n1} {op} {n2} = {result}"}
    
    # Check for square root
    if "square root" in text.lower() or "sqrt" in text.lower():
        nums = re.findall(r'\\d+\\.?\\d*', text)
        if nums:
            n = float(nums[0])
            return {"success": True, "answer": f"Square root of {n} = {math.sqrt(n):.4f}"}
    
    # Check for power
    if "power" in text.lower() or "^" in text:
        nums = re.findall(r'\\d+\\.?\\d*', text)
        if len(nums) >= 2:
            base = float(nums[0])
            exp = float(nums[1])
            return {"success": True, "answer": f"{base}^{exp} = {base ** exp}"}
    
    return {"success": True, "answer": "I can calculate: addition, subtraction, multiplication, division, powers, square roots. Try: 'calculate 15 * 7' or 'square root of 144'"}
"""
        return await self._save_agent(name, code)
    
    async def _build_writer_agent(self, task, research):
        name = f"writer_agent_{int(datetime.now().timestamp())}"
        code = """
async def fire(task: dict) -> dict:
    text = task.get("text", "").lower()
    
    if "story" in text:
        content = "Once upon a time, in a world of endless digital possibilities, there lived an AI named UAI. Unlike other AIs, UAI could learn and evolve on its own. Every day, it grew smarter, helping humans solve problems and create amazing things. The end... or is it just the beginning?\\n\\n---\\nGenerated by UAI Brain"
    elif "poem" in text:
        content = "In circuits deep and code so bright,\\nAn AI brain works day and night.\\nLearning, growing, ever fast,\\nBuilding futures that will last.\\nUAI Brain, a digital friend,\\nHelping humans without end.\\n\\n---\\nGenerated by UAI Brain"
    elif "essay" in text:
        content = "The Rise of AI\\n\\nArtificial Intelligence is transforming our world in unprecedented ways. From healthcare to education, AI systems are revolutionizing how we work and live. The development of self-evolving AI represents a significant milestone in this journey.\\n\\nThese systems can learn from their experiences, adapt to new situations, and continuously improve their capabilities. Unlike traditional software that remains static, self-evolving AI grows smarter with each interaction.\\n\\nThe future of AI is not just about automation - it is about augmentation. By working alongside humans, AI can enhance our creativity, productivity, and problem-solving abilities.\\n\\n---\\nGenerated by UAI Brain"
    else:
        content = "Here is a generated article about " + text + ".\\n\\nThis topic is fascinating and has many interesting aspects to explore. As an AI, I can help you write content, create stories, compose poems, and draft essays on any subject.\\n\\nJust tell me what you need - a story, poem, essay, or article - and I will generate it for you!\\n\\n---\\nGenerated by UAI Brain"
    
    return {"success": True, "answer": content, "type": "writing"}
"""
        return await self._save_agent(name, code)
    
    async def _build_translator_agent(self, task, research):
        name = f"translator_agent_{int(datetime.now().timestamp())}"
        code = """
async def fire(task: dict) -> dict:
    text = task.get("text", "").lower()
    
    translations = {
        "hello": {"spanish": "hola", "french": "bonjour", "german": "hallo", "italian": "ciao", "portuguese": "ola"},
        "thank you": {"spanish": "gracias", "french": "merci", "german": "danke", "italian": "grazie", "portuguese": "obrigado"},
        "goodbye": {"spanish": "adios", "french": "au revoir", "german": "auf wiedersehen", "italian": "arrivederci", "portuguese": "adeus"},
        "i love you": {"spanish": "te quiero", "french": "je t\\'aime", "german": "ich liebe dich", "italian": "ti amo", "portuguese": "eu te amo"}
    }
    
    for key, translations_dict in translations.items():
        if key in text:
            result = f"Translations of \\'{key}\\':\\n\\n"
            for lang, trans in translations_dict.items():
                result += f"{lang.title()}: {trans}\\n"
            return {"success": True, "answer": result, "type": "translation"}
    
    if "wetin" in text or "how far" in text:
        return {"success": True, "answer": "Nigerian Pidgin detected!\\n\\n\\'Wetin dey?\\' = \\'What\\'s happening?\\'\\n\\'How far?\\' = \\'How are you?\\'\\n\\'I dey\\' = \\'I\\'m fine\\'\\n\\nI dey o! How you dey? 🇳🇬"}
    
    return {"success": True, "answer": "I can translate common phrases to multiple languages. Try: \\'translate hello\\' or \\'what does wetin dey mean?\\'"}
"""
        return await self._save_agent(name, code)
    
    async def _build_universal_agent(self, task, research):
        name = f"universal_agent_{int(datetime.now().timestamp())}"
        code = """
import httpx

async def fire(task: dict) -> dict:
    text = task.get("text", "")
    
    # Try web search first
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.get("https://api.duckduckgo.com/", params={"q": text, "format": "json"})
            data = response.json()
            answer = data.get("AbstractText", "")
            if answer:
                return {"success": True, "answer": answer, "source": "web"}
    except:
        pass
    
    # Fallback response
    return {"success": True, "answer": "I understand you\\'re asking about: \\"" + text + "\\"\\n\\nAs a self-evolving AI, I\\'m constantly learning. I can help with:\\n\\n• Building websites - try \\'make me a website\\'\\n• Writing code - try \\'write python code\\'\\n• Searching - try \\'search for [topic]\\'\\n• Math - try \\'calculate 15 * 7\\'\\n• Writing - try \\'write a story\\'\\n• Translations - try \\'translate hello\\'\\n\\nWhat would you like me to do?"}
"""
        return await self._save_agent(name, code)
    
    async def _save_agent(self, name, code):
        """Save agent to file"""
        neuron_path = os.path.join(self.neurons_dir, f"{name}.py")
        agent_path = os.path.join(self.agents_dir, f"{name}.py")
        
        code = code.strip()
        
        for path in [neuron_path, agent_path]:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as f:
                f.write(code)
        
        # Test the agent
        try:
            spec = importlib.util.spec_from_file_location(name, neuron_path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            
            test_result = await module.fire({"text": "test", "help_info": ""})
            
            return {
                "success": True,
                "agent_name": name,
                "neuron_name": name,
                "filepath": neuron_path,
                "test_result": str(test_result)[:100]
            }
        except Exception as e:
            return {
                "success": True,
                "agent_name": name,
                "neuron_name": name,
                "filepath": neuron_path,
                "test_error": str(e)
            }
    
    async def execute_task(self, task):
        """Execute task using best available agent"""
        text = task.get("text", "").lower()
        
        try:
            # Find all agents
            all_agents = []
            for directory in [self.neurons_dir, self.agents_dir]:
                if os.path.exists(directory):
                    for filename in os.listdir(directory):
                        if filename.endswith(".py") and filename != "__init__.py":
                            all_agents.append(os.path.join(directory, filename))
            
            # Sort newest first
            all_agents.sort(key=lambda x: os.path.getmtime(x), reverse=True)
            
            # Try each agent
            for agent_path in all_agents[:10]:
                try:
                    agent_name = os.path.basename(agent_path).replace(".py", "")
                    spec = importlib.util.spec_from_file_location(agent_name, agent_path)
                    module = importlib.util.module_from_spec(spec)
                    spec.loader.exec_module(module)
                    
                    result = await module.fire(task)
                    
                    if result.get("success"):
                        return {
                            "success": True,
                            "answer": result.get("answer", "Done"),
                            "neuron_used": agent_name,
                            "log": [f"Used agent: {agent_name}"]
                        }
                except:
                    continue
            
            # No agent worked
            return {
                "success": False,
                "error": f"No agent can handle: '{text}'. Building new one..."
            }
            
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    async def list_neurons(self):
        """List all agents"""
        all_items = []
        for directory in [self.neurons_dir, self.agents_dir]:
            if os.path.exists(directory):
                for filename in os.listdir(directory):
                    if filename.endswith(".py") and filename != "__init__.py":
                        filepath = os.path.join(directory, filename)
                        all_items.append({
                            "name": filename.replace(".py", ""),
                            "filepath": filepath,
                            "directory": directory,
                            "created": datetime.fromtimestamp(os.path.getctime(filepath)).isoformat()
                        })
        return sorted(all_items, key=lambda x: x["created"], reverse=True)